# fly.toml app configuration file generated for listrankerapi on 2025-04-03T11:02:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'listrankerapi'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'
  GODEBUG = 'netdns=go' # Forces Go to use pure Go resolver
  FLY_RESOLVER = 'fdaa::3'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
