app = "list-ranker"

[build]
  builder = "heroku/buildpacks:go"

[env]
  GO111MODULE = "on"

[[mounts]]
  source = "data"
  destination = "/app/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
