# Use a lightweight Go image
FROM golang:1.21 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go source code
COPY . .

# Build the Go app
RUN go build -v -o /run-app ./cmd

# Use a minimal base image for running the app
FROM gcr.io/distroless/base-debian11

# Copy the compiled binary from the builder stage
COPY --from=builder /run-app /run-app

# Run the app
CMD ["/run-app"]
